// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wazaqaafywwgbxbixibf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhemFxYWFmeXd3Z2J4Yml4aWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTMzMzgsImV4cCI6MjA3MTc4OTMzOH0.-qC_yCCmxsXW5MyMU0YCQ7jAQktS9hAG69BogA47Ib0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});